### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by anatech25** [ThierryKassa/DevOps-GitHubActions#1]
Nice color has been added.

You will love the new style.

```css
h1 {
  color: #efa82e;
}
```
