### ISSUE TITLE
Suggestion: Change color

### ISSUE THREAD

**Issue by anatech25** [ThierryKassa/DevOps-GitHubActions#2]
Nice feature added

Implemented please!

```css
h1 {
  color: #efa82e;
}
```
